version: "3.9"

services:
  server_go:
    build: .
    image: api-mutant-server-go
    container_name: api_mutant
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "80:8080"
    env_file: 
      - ./.env.docker.server
    command: sh -c "/wait && /api-mutant"
    networks:  
      - backnet

  mysql:
    image: mysql:5.7
    container_name: mutant_database
    ports:
      - "3306:3306"
    env_file: 
      - ./.env.docker.database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:  
      - backnet

networks:
  backnet:
